
    menuItem
        -label "Outliner" 
        -divider 0
        -subMenu 0
        -command "switchPanelToType Outliner" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -mnemonic "?" 
        -data 0
        -radialPosition "N" 
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 1
        menuItem305;

    menuItem
        -label "Graph Editor" 
        -divider 0
        -subMenu 0
        -command "switchPanelToType GraphEditor" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -mnemonic "?" 
        -data 0
        -radialPosition "E" 
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 1
        menuItem306;

    menuItem
        -label "Dope Sheet" 
        -divider 0
        -subMenu 0
        -command "switchPanelToType DopeSheet" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -mnemonic "?" 
        -data 0
        -radialPosition "SE" 
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 1
        menuItem307;

    menuItem
        -label "Hypergraph" 
        -divider 0
        -subMenu 0
        -command "switchPanelToType Hypergraph" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -mnemonic "?" 
        -data 0
        -radialPosition "S" 
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 1
        menuItem308;

    menuItem
        -label "Dynamic Relationships" 
        -divider 0
        -subMenu 0
        -command "switchPanelToType DynRelationships" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -mnemonic "?" 
        -data 0
        -radialPosition "SW" 
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 1
        menuItem309;

    menuItem
        -label "Hypershade" 
        -divider 0
        -subMenu 0
        -command "switchPanelToType Hypershade" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -mnemonic "?" 
        -data 0
        -radialPosition "W" 
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 1
        menuItem310;

    menuItem
        -label "Render View" 
        -divider 0
        -subMenu 0
        -command "switchPanelToType RenderView" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -mnemonic "?" 
        -data 0
        -radialPosition "NW" 
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 1
        menuItem311;

    menuItem
        -label "Set Editor" 
        -divider 0
        -subMenu 0
        -command "switchPanelToType SetEditor" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -mnemonic "?" 
        -data 0
        -radialPosition "NE" 
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 1
        menuItem312;

setParent -m ..;

