#!/bin/bash
# testmayarv [ mayaversion ] [ args ]
# Maya version can be 8.5, 2008, 2009 and so forth
# 
# Uses nose to run tests defined by mayarv, options are provided to nose
base=${0%/*}
if [[ $base != /* ]]; then
	base=$PWD/$base
fi

firstArg=

# if the first argument is the maya version, we have to parse it to be able to 
# put it as first argument, inserting our args for the interpreter
if [[ $1 == 8.5 || $1 == 20?? ]]; then
	firstArg=$1
	shift
fi

startupfile=`[[ -f $base/nosestartup.py ]] && echo $base/nosestartup.py || echo $base/nosestartup.pyc`
$base/../../start/mayarv $firstArg -i $startupfile $@
