#!/bin/bash
# use maya 2008 as it requires python 2.5 - for now this is where sphinx is installed
# and has nothing to do with the quality of the generated documentation
../bin/mrv 2008 sphinx_startup.py $@ 
