#!/bin/bash
# Creates auto-summaries which requires full maya support
# use maya 2008 as it requires python 2.5 - for now this is where sphinx is installed
# and has nothing to do with the quality of the generated documentation
IFS=''
base=${0%/*}
$base/../bin/mrv 2008 $base/sphinx_autogen_startup.py $@ 
