#!/bin/sh

# FOR NOW HARDCODED TO 8.54
mayapath=/usr/autodesk/maya8.5-x64
export MAYA_LOCATION=$mayapath

# HARDCODED TO UBUNTU FOR NOW 
export LD_PRELOAD="/usr/lib64/libstdc++.so.6:/usr/lib/gcc/x86_64-linux-gnu/4.2/libgcc_s.so"

# set ldd path to maya directory
export LD_LIBRARY_PATH=$MAYA_LOCATION/lib:$LD_LIBRARY_PATH


# adjust PYTHONPATH to look for maya includes
export PYTHONPATH=$MAYA_LOCATION/lib/python*/site-packages


# set the python path to find out package
base=`/usr/bin/dirname $0`
byronimobase=$base/../py
export PYTHONPATH=$PYTHONPATH:$byronimobase


# execute the interpreter 
# TODO: parse an optional option to specify the python version or just the maya version
/usr/bin/python2.4 $@
