#!/bin/bash
# imayarv [ mayaversion ] [ args ]
# Maya version can be 8.5, 2008, 2009 and so forth
# 
# start a python shell suitable to run maya and launch ipython in it
# This is useful mainly for debugging
base=`/usr/bin/dirname $0`
firstArg=

# if the first argument is the maya version, we have to parse it to be able to 
# put it as first argument, inserting our args for the interpreter
if [[ $1 == 8.5 || $1 == 20?? ]]; then
	firstArg=$1
	shift
fi

# $base/mayarv $firstArg -i $base/ipythonstartup.py $@
